# -*- coding: utf-8 -*-
"""Sentinel_Dispatch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzd4rTZiFIXq0WOy4Q-CrM5aDRFtc9t3
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Set seed for reproducibility
np.random.seed(42)

def generate_dispatch_data(n_rows=7000):
    # 1. Basic Categorical Features
    incident_types = ['Medical', 'Structure Fire', 'Traffic Accident', 'Wellness Check', 'False Alarm']
    unit_types = ['Ambulance', 'Engine', 'Ladder', 'Rescue Squad', 'Chief']
    priorities = [1, 2, 3] # 1 is highest priority
    weather_conditions = ['Clear', 'Rain', 'Snow', 'Fog', 'Storm']

    data = {
        'Incident_ID': range(1000, 1000 + n_rows),
        'Incident_Type': np.random.choice(incident_types, n_rows, p=[0.5, 0.1, 0.2, 0.1, 0.1]),
        'Unit_Type': np.random.choice(unit_types, n_rows),
        'Priority': np.random.choice(priorities, n_rows, p=[0.3, 0.5, 0.2]),
        'Weather_Index': np.random.choice(weather_conditions, n_rows, p=[0.6, 0.2, 0.05, 0.1, 0.05]),
        'Hour_of_Day': np.random.randint(0, 24, n_rows)
    }

    df = pd.DataFrame(data)

    # 2. Define the Target Variable (TurnoutTime_Seconds) with Logic
    # Base turnout time is 60 seconds
    turnout_time = 60.0 + np.random.normal(0, 10, n_rows)

    # Apply Logic/Patterns
    for i in range(n_rows):
        # Priority Logic: Higher priority (1) is faster
        if df.loc[i, 'Priority'] == 1: turnout_time[i] -= 15
        if df.loc[i, 'Priority'] == 3: turnout_time[i] += 20

        # Weather Logic: Storms and Snow cause delays
        if df.loc[i, 'Weather_Index'] in ['Storm', 'Snow']:
            turnout_time[i] += np.random.uniform(20, 45)

        # Rush Hour Logic (7-9 AM and 4-6 PM)
        if 7 <= df.loc[i, 'Hour_of_Day'] <= 9 or 16 <= df.loc[i, 'Hour_of_Day'] <= 18:
            turnout_time[i] += np.random.uniform(15, 30)

        # Unit Logic: Engines/Ladders take longer to prep than Ambulances
        if df.loc[i, 'Unit_Type'] in ['Engine', 'Ladder']:
            turnout_time[i] += 10

    # Ensure no negative times and round to integers
    df['TurnoutTime_Seconds'] = np.maximum(turnout_time, 30).astype(int)

    return df

# Generate and Save
sentinel_data = generate_dispatch_data(5000)
sentinel_data.to_csv('sentinel_dispatch_data.csv', index=False)

print("Success! 'sentinel_dispatch_data.csv' created with 5,000 rows.")
print(sentinel_data.head())
